require_relative '../utils'

source "https://supermarket.getchef.com"

cookbook 'docker'

metadata path: Dirs.site_cookbooks('base')
metadata path: Dirs.site_cookbooks('docker-mongodb')
metadata path: Dirs.site_cookbooks('docker-redis')
