# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../utils'

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true

  config.vm.box = "kjunine/trusty64"

  config.vm.define "data" do |data|
    data.vm.hostname = "data"
    data.vm.network "private_network", ip: "192.168.8.10"
    data.vm.network "forwarded_port", guest: 2375, host: 2376

    data.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = [Dirs.cookbooks(), Dirs.site_cookbooks()]
      chef.roles_path = Dirs.roles()
      chef.environments_path = Dirs.environments()
      chef.data_bags_path = Dirs.data_bags()
      chef.add_role "mongodb"
      chef.add_role "redis"
    end
  end
end
